version: '3.7'
services:
  app:
    image: bparra/express-demo:667fall2020-redis
    ports: 
      - "4000:4000"
    networks:
      - webnet
    deploy:
      mode: replicated
      replicas: 2
      restart_policy: 
        condition: on-failure
  redis:
    image : redis:5.0.4
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: